name = "MDAL"
uuid = "b65e46c9-f591-488b-ae60-6163054eb1e2"
authors = ["Maarten Pronk", "Deltares"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
