name = "MDAL"
uuid = "b65e46c9-f591-488b-ae60-6163054eb1e2"
authors = ["Maarten Pronk", "Deltares"]
version = "0.1.0"

[deps]
MDAL_jll = "ba355c7d-02a9-511b-bb8a-ec390ce7a57a"

[compat]
julia = "1.6"
MDAL_jll = "0.9"

[extras]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Downloads"]
